### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by erikcw** [luceat-lux-vestra/search-browser-tabs-for-alfred#1]
Hey,

Since you mentioned you want to add Firefox support, just wanted to let you know that I have a small library that does just that.  Hope it is helpful.

https://github.com/erikcw/firefox-tabs

**Comment by luceat-lux-vestra** [comment]
I dug into this, but it seems I can't make it work.

`Firefox` doesn't expose the required methods AFAIK.
I think it can be, but it's not easy as `Safari` or `Chrome` or some other browsers based on `Chromium` I think.

BTW thanks!

**Comment by erikcw** [comment]
You need to pass the path to your FireFox profile directory to the script.

`fftabs "~/Library/Application Support/Firefox/Profiles/410vnzik.Default User/sessionstore-backups/recovery.jsonlz4"` 

Specifically change out `410vnzik.Default User` to the unique directory name on your system.

**Comment by luceat-lux-vestra** [comment]
I know that, I tested your `fftabs` library and saw raw json data using other lib.  
but `Firefox` has lack of support for AppleScript, unlikely other browsers.

I tried a couple of ways I thought `It's not good, but it should work`, but no luck.
I feel shame on my ignorance.

**Comment by luceat-lux-vestra** [comment]
firefox/opera support added to this project. https://github.com/luceat-lux-vestra/alfred-tabs-improved
