### ISSUE TITLE
[Request] Use the tab icon in alfred

### ISSUE THREAD

**Issue by krishnakumar-kapil** [luceat-lux-vestra/search-browser-tabs-for-alfred#4]
Would it be possible to use the tab icon in the Alfred dropdown rather than just using the chrome or safari icon? Thanks

**Comment by luceat-lux-vestra** [comment]
icon relevant codes you said are hard coded in `filter.rb`.
Safari uses safari icon, and all the others uses default icon for them.

I think alfred also uses  default icon for app like this workflow -> https://www.alfredforum.com/topic/5874-16-get-app-icon/

Thanks.
